### ISSUE TITLE
AUSCERT miner grabbing raw HTML

### ISSUE THREAD

**Issue by JoshSchwarz** [PaloAltoNetworks/minemeld-core#147]
An issue appears to exist in auscert.py where it appears to grab raw HTML and insert this into the pipeline along with the targeted feed. [Example](https://imgur.com/a/JmDgW).

It appears to be coming from the 'access denied' page (https://www.auscert.org.au/render.html?it=9123). When obtaining the files manually I noticed that you are directed to this page before logging in, however a quick glance at the code suggests that you are already handling this auth then download system.

I had no idea where to start investigating this as the logs don't seem particularly helpful, so please let me know! Happy to send whatever you need through.

**Comment by jtschichold** [comment]
That's not nice. Would you have some time for a joint debugging session ? You can send me an email at lmori@paloaltonetworks.com if it's ok for you.

In the meantime you could use the TAXII Miner to connect to the AUSCERT feeds, the fine guys from the CERT have a guide on how to use MineMeld to consume their feeds.

**Comment by JoshSchwarz** [comment]
I have since been unable to reproduce this bug. If I come across it again I will send you an email. :)

**Comment by jtschichold** [comment]
This should be fixed with #184
