### ISSUE TITLE
API to append results in ok, but indicator list is not updated as seen in webUI

### ISSUE THREAD

**Issue by acstanton515** [PaloAltoNetworks/minemeld-core#168]
Running 0.9.30

Per a post in community, can use:

`/data/<datafilename>/append`

to append an indicator to a list.

Tried this, but did not observe indicator added to list from Admin UI:

```
curl -XPOST --insecure -H "Content-Type: application/json" -u REDACT https://REDACT/config/data/wlWhiteListIPv4/append?h=wlWhiteListIPv4 -d '{
    "indicator": "1.1.1.1",
    "type": "IPv4",
    "share_level": "green",
    "comment": "Test"
}'
```

Went to:

`/opt/minemeld/local/config`

Found append API calls that I made in a file called

`wlWhiteListIPv4.yml`

Observed other lists had a _indicator in the name

`NAME_indicator.yml`

Tried append on another list, and found the appends going to NAME.yml.

Tried to update the curl with _indicator, but get:

```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

Believe at some point '_indicator' was introduced to filename path, but not updated in the API code.

https://github.com/PaloAltoNetworks/minemeld-core/blob/develop/minemeld/flask/configapi.py#L635

I believe this bug is still present in 0.9.3.2 which is current master.

**Comment by jtschichold** [comment]
Hi @acstanton515 !
the datafilename to add indicators to a local node should be `NAME_indicators`. The API should look like this:

```
curl -XPOST -H "Content-Type: application/json" -u REDACT https://REDACT/config/data/wlWhiteListIPv4_indicators/append?h=wlWhiteListIPv4 -d '{
     "indicator": "1.1.1.100",
     "type": "IPv4",
     "share_level": "green",
     "comment": "Test"
}'
```

**Comment by acstanton515** [comment]
This works.  But, is it ideal?  Should API caller know that the node name should be appended with _indicators?

Is it still a bug or you think it is expected/desired functionality?

**Comment by jtschichold** [comment]
This is expected:
- NAME_indicators.yml files are used by nodes of class minemeld.ft.local.Yaml* to store indicators
- API client should know the class of the nodes before submitting the indicators
- different class of nodes have different ways of storing indicators and API are not class specific

I have plans to create a new, improved node class for storing local indicators based on a proper database and with age out of indicators. This way you could submit new indicators with a TTL and the node will take care of expiring the indicators after the TTL expires.
