### ISSUE TITLE
drop update message

### ISSUE THREAD

**Issue by santi10** [PaloAltoNetworks/minemeld-core#175]
Hi,
 
I've just created a new node and I'm seeing events such us: DROP_UPDATE on aggregator type. 
 
My miner has all domain list but the aggregator has this meessge with "drop_update", do you know it??? Why???
 
Thanks a lot

**Comment by jtschichold** [comment]
Closing as it was answered here: https://live.paloaltonetworks.com/t5/MineMeld-Discussions/Drop-update/m-p/145099#M829
