### ISSUE TITLE
Minemeld not accessible after reboot

### ISSUE THREAD

**Issue by cuongdinh** [PaloAltoNetworks/minemeld-core#176]
Hello,

I tried to create a miner (I believe a generic IPv4 list), committed it, but the system stopped for some reason, couldn't restart the 'system'. So I rebooted the whole box (Ubuntu 14.04), didn't fix it, even after a shutdown. Now I can't even access the web interface. All of my services are running. I think something got stuck but I couldn't figure out. Any help would be greatly appreciated.

sudo -u minemeld /opt/minemeld/engine/current/bin/supervisorctl -c /opt/minemeld/local/supervisor/config/supervisord.conf status
minemeld-engine                  RUNNING   pid 2261, uptime 0:00:31
minemeld-supervisord-listener    RUNNING   pid 2260, uptime 0:00:31
minemeld-traced                  RUNNING   pid 2262, uptime 0:00:31
minemeld-web                     RUNNING   pid 2263, uptime 0:00:31

Thank you,

**Comment by jtschichold** [comment]
Hi,
for _system_ you mean MineMeld or the Ubuntu VM itself ?
when you say you can't access the web-interface, you mean you can't see the login screen ? or that the authentication fails ?

**Comment by HelioCD** [comment]
For 'system' being stopped, I meant Minemeld system.
When I tried to access the interface, it wouldn't load (no login screen). Did an nmap scan and port 443 wasn't listening either, even though all minemeld services are running.
Let me know if you'd like to look at any logs.
Thanks!

**Comment by cuongdinh** [comment]
For 'system' being stopped, I meant Minemeld system.
When I tried to access the interface, it wouldn't load (no login screen). Did an nmap scan and port 443 wasn't listening either, even though all minemeld services are running.
Let me know if you'd like to look at any logs.
Thanks!

**Comment by jtschichold** [comment]
is nginx running on the VM ?
Port 443 is opened by nginx, nginx then forwards requests to minemeld-web service

**Comment by cuongdinh** [comment]
Thanks for the tip! I found the issue.

I couldn't start nginx either. Looked into /var/log/nginx/error.log and found the error below. Googled a bit and removed the "minemeld-web.dpkg-dist" file and nginx was able to start. Minemeld is back online.

2017/03/04 12:46:26 [emerg] 19698#0: duplicate upstream "app_server" in /etc/nginx/sites-enabled/minemeld-web.dpkg-dist:1

Thanks!
