### ISSUE TITLE
"Errno bad ca_certs" with certain miners

### ISSUE THREAD

**Issue by victor1tnet** [PaloAltoNetworks/minemeld-core#214]
After the auto update (a bit after that) to 0.9.38.post1 , I started receiving these : 

2017-05-06T06:41:56 (25675)basepoller._poll ERROR: Exception in polling loop for ransomwaretracker_combined_URL: [Errno bad ca_certs: '/opt/minemeld/local/certs/bundle.crt'] [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib'

For each of the miners below : 

CLASS	minemeld.ft.http.HttpFT
PROTOTYPE	dshield.block

CLASS	minemeld.ft.http.HttpFT
PROTOTYPE	ransomwaretracker.RW_URLBL

CLASS	minemeld.ft.http.HttpFT
PROTOTYPE	ransomwaretracker.CW_C2_URLBL

All using the minemeld.ft.http.HttpFT class and connecting to an HTTPS feed

When it comes to other miners like below and that is connecting to an HTTP feed : 

CLASS	minemeld.ft.csv.CSVFT
PROTOTYPE	bambenekconsulting.c2_dommasterlist_high

Everything is working fine

As the error is saying , the file located in "/opt/minemeld/local/certs/bundle.crt" is missing. 

Does this mean that MineMeld is failing to recognize/download pub cert from the feed location ?

Connectivity is done via proxy for both HTTP and HTTPS but it wasn't an issue before the update.

Any help appreciated!

**Comment by jtschichold** [comment]
Hi @victor1tnet,
please do the following:
```
# make sure you have the latest package release
$ sudo /usr/sbin/minemeld-auto-update
# regenerate the CA bundle
$ sudo -u minemeld mm-cabundle-update
# restart the engine (shouldn't be needed)
$ sudo -u minemeld mm-supervisorctl restart minemeld-engine
```

**Comment by victor1tnet** [comment]
Thanks, i can confirm that regenerating the CA bundle and restarting the engine did the trick. 

As mentioned by another user in https://live.paloaltonetworks.com/t5/MineMeld-Discussions/Minemeld-updated-and-now-I-am-getting-cert-errors-on-some-sites/m-p/155473#M1042 , I get the below warning when running the  line "sudo -u minemeld mm-cabundle-update"

"
017-05-08T07:04:14 (13103)cacert_merge.main INFO: config: {'cafile': ['/opt/minemeld/local/certs/site/'], 'dst': '/opt/minemeld/local/certs/bundle.crt', 'config': '/opt/minemeld/local/certs/cacert-merge-config.yml', 'no_merge_certifi': False}
WARNING: old python version (< 2.7.9) - certificate verification not performed "

The CA bundle IS REGENERATED, even though we get the warning above. 

--- 

This was caused when the auto update failed in restarting NGINX and failed in regenerating the CA certs afterwards.

**Comment by jtschichold** [comment]
Hi @victor1tnet,
could you share the error thrown by the nginx service ? I will handle that in the next release.

Luigi
