### ISSUE TITLE
Json Miner should also work with Token-Authentication

### ISSUE THREAD

**Issue by idev** [PaloAltoNetworks/minemeld-core#216]
Hello,

I have a Feed which requires Token Authentication in the Header:
curl -H "Authorization: Bearer <TOKEN>" "https://api-url.com/api/v1/iocs?first_seen_since=2016-1-1"

As far as I know this is currently not possible?

Kind regards

**Comment by jtschichold** [comment]
Hi @idev,
you are right, this is not possible today. Two solutions:
- develop an external extension subclassing minemeld.ft.json.SimpleJSON and override *configure* and *_build_iterator* methods to load a custom header from the config file and then use it in the request. Check PaloAltoNetworks/youtube-miner for an example of an external extension.
- create a pull request to minemeld-core with the above logic

I have marked this as an *enhancement*.

Thanks,
luigi

**Comment by idev** [comment]
Pull Request created in DEV Branch

**Comment by jtschichold** [comment]
PR approved, thanks !

**Comment by Ergopeoxy** [comment]
Was there any updates on if this feature is now available ?
