### ISSUE TITLE
auscert miner authentication change

### ISSUE THREAD

**Issue by salaisuuxia** [PaloAltoNetworks/minemeld-core#225]
instead of basic authentication, auscert feed now requires a header with the key of "API-Key"

this simplifies the feed pull considerably.
the data format may have changed also.

**Comment by jtschichold** [comment]
Hi @salaisuuxia,
#226 and PaloAltoNetworks/minemeld-webui#104 have been merged to support the API-Key. This will make into the next release.

Thanks for the heads up !

luigi
