### ISSUE TITLE
Restore failed with: error scheduling restore internal server error

### ISSUE THREAD

**Issue by provonet** [PaloAltoNetworks/minemeld-core#314]
When we try to restore a backup created through the ui the restore failed with the following error:
error scheduling restore internal server error the only logmessage related to the issue is the following:

127.0.0.1 - - [20/Feb/2019:09:12:30 +0100] "POST /status/backup/import/zdZ4n9/restore?_=1550650350 HTTP/1.0" 500 68 "https://minemeld-acc.example.com/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36"

The restore function was able to upload the zip file to the /tmp folder and running mm-restore from the commandline works.

Minemeld version: 0.9.52

**Comment by provonet** [comment]
I discovered that MINEMELD_RESTORE_PATH was missing in the api yaml file. After adding MINEMELD_RESTORE_PATH: /opt/minemeld/engine/current/bin/mm-restore I was able to restore a backup.

**Comment by jtschichold** [comment]
Hi @provonet,
thanks. I have fixed the ansible script to include the 
MINEMELD_RESTORE_PATH.
https://github.com/PaloAltoNetworks/minemeld-ansible/blob/master/roles/minemeld/templates/10-defaults.yml.j2#L25
