### ISSUE TITLE
Some error message spelling typos in minemeld/ft/base.py

### ISSUE THREAD

**Issue by kevinsteves** [PaloAltoNetworks/minemeld-core#37]
$ find . -name '*.py' -exec grep -s recev x {} \;
./minemeld-core/minemeld/ft/base.py:            LOG.error("update recevied from checkpointed source")
./minemeld-core/minemeld/ft/base.py:            raise AssertionError("update recevied from checkpointed source")
./minemeld-core/minemeld/ft/base.py:            LOG.error("withdraw recevied from checkpointed source")
./minemeld-core/minemeld/ft/base.py:            raise AssertionError("withdraw recevied from checkpointed source")

**Comment by jtschichold** [comment]
Fixed. Thanks
