### ISSUE TITLE
Output Syslog in CEF Format

### ISSUE THREAD

**Issue by Forseti-** [PaloAltoNetworks/minemeld-core#39]
Hi everyone,

Currently we have an syslog to local logstash prototype available as an output. We however utilize ArcSight and would love to be able to receive either the 'logstash' syslog or a CEF formatted one. CEF syntax can be found [here](https://www.protect724.hpe.com/servlet/JiveServlet/downloadBody/1072-102-9-20354/CommonEventFormatv23.pdf).

Creating such an prototype would support the ArcSight community out there!

Regards,
Forseti

**Comment by jtschichold** [comment]
Hi Forseti,
that's a super interesting idea. We could create a dedicated node to CEF or try to use the CEF codec inside logstash. I will look into this.

Thanks !
luigi

**Comment by jtschichold** [comment]
Implemented as external extension, see https://github.com/PaloAltoNetworks/minemeld-cef
